name: "CI"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linting
        run: yarn lint

      - name: Run total-asset-size-action
        uses: ./
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          build_command: "yarn build"
          file_patterns: '["dist/*.js", "lib/**/*.js"]'
